"""add spend_limits and audit_logs

Revision ID: 784d448bdd7c
Revises: 9437cd203d39
Create Date: 2026-05-21 19:54:55.761492
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '784d448bdd7c'
down_revision: Union[str, None] = '9437cd203d39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('action_proposal_id', sa.String(length=64), nullable=True),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('risk_level', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('payload_redacted', sa.JSON(), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('reversible', sa.Boolean(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action_proposal_id'), 'audit_logs', ['action_proposal_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('spend_limits',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('cap_minor', sa.Integer(), nullable=False),
    sa.Column('spent_minor', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spend_limits_user_id'), 'spend_limits', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spend_limits_user_id'), table_name='spend_limits')
    op.drop_table('spend_limits')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_proposal_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
