"""add daily_briefings

Revision ID: 7bc15aff0b5b
Revises: 26587d980acc
Create Date: 2026-05-21 18:27:39.492174
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7bc15aff0b5b'
down_revision: Union[str, None] = '26587d980acc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_briefings',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('user_feedback', sa.String(length=16), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_briefing_user_date')
    )
    op.create_index(op.f('ix_daily_briefings_date'), 'daily_briefings', ['date'], unique=False)
    op.create_index(op.f('ix_daily_briefings_user_id'), 'daily_briefings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_briefings_user_id'), table_name='daily_briefings')
    op.drop_index(op.f('ix_daily_briefings_date'), table_name='daily_briefings')
    op.drop_table('daily_briefings')
    # ### end Alembic commands ###
